### ISSUE TITLE
Can't tell what starlark Builtin cannot be converted to Python

### ISSUE THREAD

**Issue by colindean** [caketop/python-starlark-go#143]
I can't tell which property of the final output of my Starlark script is not convertible.

```
$ python3 test.py test.star
Traceback (most recent call last):
  File "/Users/Z003XC4/Source/Target/TargetOSS/python-poetry/test.py", line 12, in <module>
    print(s.eval("main([])"))
starlark_go.errors.ConversionError: Don't know how to convert *starlark.Builtin to Python value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Z003XC4/Source/Target/TargetOSS/python-poetry/test.py", line 14, in <module>
    print(e.backtrace)
AttributeError: 'ConversionError' object has no attribute 'backtrace'
```

Test code:

```python
import sys

from starlark_go import Starlark
from starlark_go.errors import EvalError, ConversionError

s = Starlark()

with open(sys.argv[1], 'r') as input_file:
    s.exec(input_file.read())

try:
    print(s.eval("main([])"))
except (EvalError, ConversionError) as e:
    print(e.backtrace)
```

The test code is working with simple dictionaries so it might be something else fancier I'm (unknowingly) doing that's not resolving to something convertible.

**Comment by jordemort** [comment]
Can you share the Starlark that triggers this as well?

**Comment by jordemort** [comment]
It looks like you're trying to return a reference to a function somehow? A [Builtin](https://pkg.go.dev/go.starlark.net@v0.0.0-20230122040757-066229b0515d/starlark#Builtin) is a Go function that is callable from Starlark. I'd like for this module to support returning Callables back to Python but it doesn't at this time.

**Comment by colindean** [comment]
I introduce a `print()` of the final output and tracked it down to basically this:

```
"slack": {"needs": <built-in method keys of dict value>, 
```

and this is the minimum reproduction:

```starlark
def stage_slack_notify(stage_names):
    return {"name": "slack", "needs": stage_names}

def main(ctx):
    build_stages = {"something": [], "something_else": []}

    stages = [build_stages] + [stage_slack_notify(build_stages.keys)]
    final = {
        'version': '1',
        'stages': stages,
    }

    print(final)

    return final
```

Can you spot the error?

`Array.keys()` is a function and I forgot `()`. 🙃 PEBKAC.

But I still feel like there's a better way to communicate the error, perhaps by telling exactly what wasn't able to be converted, with some path to it if possible.

**Comment by jordemort** [comment]
Keeping track of the path to the value would be doable but maybe kinda ugly. I think we'd have to add a `path` parameter to every function in [starlark_to_python.go](https://github.com/caketop/python-starlark-go/blob/main/starlark_to_python.go) and have `starlark[Dict|Tuple|Set|List]ToPython` append keys to it before passing it along to the next function.
