### ISSUE TITLE
Add link to docs in repo 'website' section?

### ISSUE THREAD

**Issue by tadamcz** [caketop/python-starlark-go#175]
This is quite a silly thing, but I originally missed the 'docs' badge here, which is the only link to the documentation on the README:
<img width="440" alt="image" src="https://user-images.githubusercontent.com/43300673/228845584-a17c242c-bf1a-4830-8515-06d3a48a86b9.png">

When you Cmd+F on the page for the strings `docs`, the badge is not matched (at least in Chrome). So it took me a little bit of time to find the docs 🤦, which I only did when I cloned the repo and opened the README in a markdown editor.

Adding a link to `https://python-starlark-go.readthedocs.io/` in the 'website' section on the right-hand side of the repo would be very low effort, and potentially might help at least one other person get started with your library 🙂.

**Comment by jordemort** [comment]
Good idea, I've added the link.
